"""add is_active to customers

Revision ID: 159a44792711
Revises: ccfed4f96ef7
Create Date: 2026-02-22 16:12:25.870010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '159a44792711'
down_revision: Union[str, Sequence[str], None] = 'ccfed4f96ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.create_index(op.f('ix_customers_is_active'), 'customers', ['is_active'], unique=False)
    op.drop_constraint(op.f('customers_company_id_fkey'), 'customers', type_='foreignkey')
    op.drop_column('customers', 'company_id')
    op.alter_column('inventory_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.drop_constraint(op.f('invoice_items_invoice_id_fkey'), 'invoice_items', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('invoices_customer_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_work_order_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'work_orders', ['work_order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoices', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.add_column('vehicles', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_vehicles_is_active'), 'vehicles', ['is_active'], unique=False)
    op.drop_constraint(op.f('vehicles_customer_id_fkey'), 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('work_orders_customer_id_fkey'), 'work_orders', type_='foreignkey')
    op.drop_constraint(op.f('work_orders_mechanic_id_fkey'), 'work_orders', type_='foreignkey')
    op.drop_constraint(op.f('work_orders_vehicle_id_fkey'), 'work_orders', type_='foreignkey')
    op.create_foreign_key(None, 'work_orders', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'work_orders', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'work_orders', 'users', ['mechanic_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.create_foreign_key(op.f('work_orders_vehicle_id_fkey'), 'work_orders', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(op.f('work_orders_mechanic_id_fkey'), 'work_orders', 'users', ['mechanic_id'], ['id'])
    op.create_foreign_key(op.f('work_orders_customer_id_fkey'), 'work_orders', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicles_customer_id_fkey'), 'vehicles', 'customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_vehicles_is_active'), table_name='vehicles')
    op.drop_column('vehicles', 'is_active')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_work_order_id_fkey'), 'invoices', 'work_orders', ['work_order_id'], ['id'])
    op.create_foreign_key(op.f('invoices_customer_id_fkey'), 'invoices', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_items_invoice_id_fkey'), 'invoice_items', 'invoices', ['invoice_id'], ['id'])
    op.alter_column('inventory_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('customers', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('customers_company_id_fkey'), 'customers', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_customers_is_active'), table_name='customers')
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.drop_column('customers', 'is_active')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_column('companies', 'is_active')
    # ### end Alembic commands ###
