"""inventory full with image

Revision ID: 4bffa679d1a9
Revises: cea0d27056c7
Create Date: 2026-01-30 23:19:50.967617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bffa679d1a9'
down_revision: Union[str, Sequence[str], None] = 'cea0d27056c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_code', sa.String(length=80), nullable=False),
    sa.Column('part_name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('sub_category', sa.String(length=120), nullable=True),
    sa.Column('barcode', sa.String(length=80), nullable=True),
    sa.Column('oem_reference', sa.String(length=120), nullable=True),
    sa.Column('engine_type', sa.String(length=80), nullable=True),
    sa.Column('vehicle_make', sa.String(length=80), nullable=True),
    sa.Column('vehicle_model', sa.String(length=80), nullable=True),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('technical_notes', sa.Text(), nullable=True),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_quantity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('auto_reorder_enabled', sa.Boolean(), nullable=False),
    sa.Column('critical_part', sa.Boolean(), nullable=False),
    sa.Column('seasonal', sa.Boolean(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_price_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_level_a', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_level_b', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_level_c', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('taxable', sa.Boolean(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_part_number', sa.String(length=120), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('last_purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_purchase_date', sa.Date(), nullable=True),
    sa.Column('average_monthly_usage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_used_date', sa.Date(), nullable=True),
    sa.Column('times_sold', sa.Integer(), nullable=False),
    sa.Column('auto_reorder_last_run', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('editable_price', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_barcode'), 'inventory_items', ['barcode'], unique=False)
    op.create_index(op.f('ix_inventory_items_brand'), 'inventory_items', ['brand'], unique=False)
    op.create_index(op.f('ix_inventory_items_category'), 'inventory_items', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_items_created_by'), 'inventory_items', ['created_by'], unique=False)
    op.create_index(op.f('ix_inventory_items_engine_type'), 'inventory_items', ['engine_type'], unique=False)
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_items_location'), 'inventory_items', ['location'], unique=False)
    op.create_index(op.f('ix_inventory_items_oem_reference'), 'inventory_items', ['oem_reference'], unique=False)
    op.create_index(op.f('ix_inventory_items_part_code'), 'inventory_items', ['part_code'], unique=False)
    op.create_index(op.f('ix_inventory_items_part_name'), 'inventory_items', ['part_name'], unique=False)
    op.create_index(op.f('ix_inventory_items_sub_category'), 'inventory_items', ['sub_category'], unique=False)
    op.create_index(op.f('ix_inventory_items_supplier_id'), 'inventory_items', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_updated_by'), 'inventory_items', ['updated_by'], unique=False)
    op.create_index(op.f('ix_inventory_items_vehicle_make'), 'inventory_items', ['vehicle_make'], unique=False)
    op.create_index(op.f('ix_inventory_items_vehicle_model'), 'inventory_items', ['vehicle_model'], unique=False)
    op.create_table('inventory_item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_item_images_id'), 'inventory_item_images', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_item_images_item_id'), 'inventory_item_images', ['item_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity_moved', sa.Integer(), nullable=False),
    sa.Column('movement_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('related_job_id', sa.Integer(), nullable=True),
    sa.Column('movement_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_item_id'), 'inventory_movements', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_related_job_id'), 'inventory_movements', ['related_job_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_user_id'), 'inventory_movements', ['user_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_id'), 'stock_movements', ['id'], unique=False)
    op.create_index(op.f('ix_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('mechanic_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['mechanic_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_item_type'), 'invoice_items', ['item_type'], unique=False)
    op.alter_column('companies', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('companies', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.drop_index(op.f('ix_companies_customer_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.drop_constraint(op.f('companies_customer_id_fkey'), 'companies', type_='foreignkey')
    op.drop_column('companies', 'customer_id')
    op.add_column('customers', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('customers', sa.Column('company_id', sa.Integer(), nullable=True))
    op.alter_column('customers', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('customers', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.drop_index(op.f('ix_customers_account_no'), table_name='customers')
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_foreign_key(None, 'customers', 'companies', ['company_id'], ['id'])
    op.drop_column('customers', 'account_no')
    op.drop_column('customers', 'full_name')
    op.alter_column('roles', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('roles', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('vehicles', sa.Column('unit_number', sa.String(length=50), nullable=True))
    op.alter_column('vehicles', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('vehicles', 'vin',
               existing_type=sa.TEXT(),
               type_=sa.String(length=17),
               nullable=True)
    op.alter_column('vehicles', 'make',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('vehicles', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('vehicles', 'customer_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.drop_index(op.f('ix_vehicles_company_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_customer_id'), table_name='vehicles')
    op.create_index(op.f('ix_vehicles_unit_number'), 'vehicles', ['unit_number'], unique=False)
    op.drop_constraint(op.f('vehicles_company_id_fkey'), 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('vehicles_company_id_fkey'), 'vehicles', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_vehicles_unit_number'), table_name='vehicles')
    op.create_index(op.f('ix_vehicles_customer_id'), 'vehicles', ['customer_id'], unique=False)
    op.create_index(op.f('ix_vehicles_company_id'), 'vehicles', ['company_id'], unique=False)
    op.alter_column('vehicles', 'customer_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('vehicles', 'model',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vehicles', 'make',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vehicles', 'vin',
               existing_type=sa.String(length=17),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('vehicles', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('vehicles', 'unit_number')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('customers', sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('account_no', sa.INTEGER(), sa.Identity(always=False, start=1000, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.create_index(op.f('ix_customers_account_no'), 'customers', ['account_no'], unique=True)
    op.alter_column('customers', 'email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customers', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customers', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('customers', 'company_id')
    op.drop_column('customers', 'name')
    op.add_column('companies', sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('companies_customer_id_fkey'), 'companies', 'customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_customer_id'), 'companies', ['customer_id'], unique=False)
    op.alter_column('companies', 'name',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('companies', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_invoice_items_item_type'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_stock_movements_item_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_inventory_movements_user_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_related_job_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_movement_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_item_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_inventory_item_images_item_id'), table_name='inventory_item_images')
    op.drop_index(op.f('ix_inventory_item_images_id'), table_name='inventory_item_images')
    op.drop_table('inventory_item_images')
    op.drop_index(op.f('ix_inventory_items_vehicle_model'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_vehicle_make'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_updated_by'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_supplier_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_sub_category'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_part_name'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_part_code'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_oem_reference'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_location'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_engine_type'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_created_by'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_category'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_brand'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_barcode'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
