"""add work_order_items and invoice links

Revision ID: b5c66b3dc0ee
Revises: 017f85272b77
Create Date: 2026-03-01 16:58:54.410761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c66b3dc0ee'
down_revision: Union[str, Sequence[str], None] = '017f85272b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('inventory_item_id', sa.Integer(), nullable=True))
    op.add_column('invoice_items', sa.Column('work_order_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invoice_items_inventory_item_id'), 'invoice_items', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_work_order_item_id'), 'invoice_items', ['work_order_item_id'], unique=False)
    op.create_foreign_key(None, 'invoice_items', 'inventory_items', ['inventory_item_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invoice_items', 'work_order_items', ['work_order_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_items_work_order_item_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_inventory_item_id'), table_name='invoice_items')
    op.drop_column('invoice_items', 'work_order_item_id')
    op.drop_column('invoice_items', 'inventory_item_id')
    # ### end Alembic commands ###
