"""user_roles_and_vin_validation

Revision ID: c54e5b7dc67b
Revises: 0da7a2181a73
Create Date: 2026-01-25 13:39:43.802199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54e5b7dc67b'
down_revision: Union[str, Sequence[str], None] = '0da7a2181a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    'roles',
    sa.Column('id', sa.BigInteger(), primary_key=True),
    sa.Column('name', sa.Text(), nullable=False),

    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint(op.f('companies_customer_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'customers', ['customer_id'], ['id'])
    op.alter_column('vehicles', 'vin',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_vehicles_vin'), table_name='vehicles')
    op.create_index(op.f('ix_vehicles_vin'), 'vehicles', ['vin'], unique=True)
    op.drop_constraint(op.f('vehicles_company_id_fkey'), 'vehicles', type_='foreignkey')
    op.drop_constraint(op.f('vehicles_customer_id_fkey'), 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicles_customer_id_fkey'), 'vehicles', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('vehicles_company_id_fkey'), 'vehicles', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_vehicles_vin'), table_name='vehicles')
    op.create_index(op.f('ix_vehicles_vin'), 'vehicles', ['vin'], unique=False)
    op.alter_column('vehicles', 'vin',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_customer_id_fkey'), 'companies', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
