"""add unit_cost to inventory_movements

Revision ID: ccfed4f96ef7
Revises: 4bffa679d1a9
Create Date: 2026-02-15 23:26:59.930865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccfed4f96ef7'
down_revision: Union[str, Sequence[str], None] = '4bffa679d1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_item_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_index('ix_item_images_item_pos', 'inventory_item_images', ['item_id', 'position'], unique=False)
    op.create_index('ix_inventory_search', 'inventory_items', ['part_name', 'brand', 'category', 'sub_category'], unique=False)
    op.create_unique_constraint('uq_inventory_part_code', 'inventory_items', ['part_code'])
    op.add_column('inventory_movements', sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_index('ix_movement_item_date', 'inventory_movements', ['item_id', 'movement_date'], unique=False)
    op.create_index('ix_movement_type_date', 'inventory_movements', ['movement_type', 'movement_date'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_work_order_id'), 'invoices', ['work_order_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.add_column('vehicles', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('vehicles', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_vehicles_customer_id'), 'vehicles', ['customer_id'], unique=False)
    op.create_index(op.f('ix_work_orders_customer_id'), 'work_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_work_orders_mechanic_id'), 'work_orders', ['mechanic_id'], unique=False)
    op.create_index(op.f('ix_work_orders_vehicle_id'), 'work_orders', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_vehicle_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_mechanic_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_customer_id'), table_name='work_orders')
    op.drop_index(op.f('ix_vehicles_customer_id'), table_name='vehicles')
    op.drop_column('vehicles', 'updated_at')
    op.drop_column('vehicles', 'created_at')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_invoices_work_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index('ix_movement_type_date', table_name='inventory_movements')
    op.drop_index('ix_movement_item_date', table_name='inventory_movements')
    op.drop_column('inventory_movements', 'unit_cost')
    op.drop_constraint('uq_inventory_part_code', 'inventory_items', type_='unique')
    op.drop_index('ix_inventory_search', table_name='inventory_items')
    op.drop_index('ix_item_images_item_pos', table_name='inventory_item_images')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    op.create_table('stock_movements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('stock_movements_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_movements_pkey'))
    )
    op.create_index(op.f('ix_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_id'), 'stock_movements', ['id'], unique=False)
    # ### end Alembic commands ###
