"""add markup_percent to inventory_items

Revision ID: e88ab0ddcc4c
Revises: quotes_lifecycle_001
Create Date: 2026-03-19 22:28:31.541482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e88ab0ddcc4c'
down_revision: Union[str, Sequence[str], None] = 'quotes_lifecycle_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_legacy_id'), table_name='stock_movements_legacy')
    op.drop_index(op.f('ix_stock_movements_legacy_item_id'), table_name='stock_movements_legacy')
    op.drop_table('stock_movements_legacy')
    op.drop_index(op.f('ix_inventory_items_legacy_id'), table_name='inventory_items_legacy')
    op.drop_index(op.f('ix_inventory_items_legacy_sku'), table_name='inventory_items_legacy')
    op.drop_table('inventory_items_legacy')
    op.alter_column('inventory_item_images', 'alt_text',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('inventory_item_images', 'position',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_item_images_item_pos'), table_name='inventory_item_images')
    op.add_column('inventory_items', sa.Column('markup_percent', sa.Numeric(5, 2), nullable=False, server_default='0'))
    op.alter_column('invoices', 'document_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('invoices', 'settlement_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'settlement_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('invoices', 'document_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('inventory_items', 'markup_percent')
    op.create_index(op.f('ix_item_images_item_pos'), 'inventory_item_images', ['item_id', 'position'], unique=False)
    op.alter_column('inventory_item_images', 'position',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('inventory_item_images', 'alt_text',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.create_table('inventory_items_legacy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_items_legacy_pkey'))
    )
    op.create_index(op.f('ix_inventory_items_legacy_sku'), 'inventory_items_legacy', ['sku'], unique=True)
    op.create_index(op.f('ix_inventory_items_legacy_id'), 'inventory_items_legacy', ['id'], unique=False)
    op.create_table('stock_movements_legacy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items_legacy.id'], name=op.f('stock_movements_legacy_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_movements_legacy_pkey'))
    )
    op.create_index(op.f('ix_stock_movements_legacy_item_id'), 'stock_movements_legacy', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_legacy_id'), 'stock_movements_legacy', ['id'], unique=False)
    # ### end Alembic commands ###
